### ISSUE TITLE
Journal field missing from Mendeley remote bib

### ISSUE THREAD

**Issue by rudvfaden** [LaTeXing/LaTeXing#105]

**Comment by csch0** [comment]
Any special data type?

**Comment by rudvfaden** [comment]
I'm not sure what you mean

**Comment by csch0** [comment]
Is the journal field always missing or just for specific entry tyre like journal or journal_article?!

**Comment by rudvfaden** [comment]
The journal field is always missing

**Comment by ntezak** [comment]
This has been a big problem for me, please fix!

**Comment by minihessel** [comment]
I only seem to get @misc for webpages, and no "downloaded from" link is added. Could this be related to this bug @csch0  ?

**Comment by csch0** [comment]
Yes both related and fixed in 1.2.9 (release later tonight0. Please keep posting here for any other problem

**Comment by rudvfaden** [comment]
The problem persist in version 1.2.9

**Comment by csch0** [comment]
Did you rebuild your cache?

**Comment by minihessel** [comment]
@csch0 it fixed many of the entries, but web pages still don't have any links. They only appear like this in remote.bib:

@misc{Benson2009Personal,
	author = {Benson, Jim},
	title = {Personal Kanban},
	year = 2009
}

**Comment by rudvfaden** [comment]
Rebuilding cache made the journal field show up. But it display the publisher and not the journal.

**Comment by csch0** [comment]
@minihessel for me a webpage as a link just checked it

**Comment by csch0** [comment]
@rudvfaden could you please try the latest testing version?

**Comment by minihessel** [comment]
Did you mean that web page creates a link when you try @csch0 ?

**Comment by csch0** [comment]
Yes in the remote.bib I have the following for a website

@misc{Lutz2011Programming,
	author = {Lutz, Mark},
	keywords = {python programming},
	title = {Programming Python: Amazon.co.uk: Mark Lutz: 9780596158101: Books},
	url = {http://www.amazon.co.uk/Programming-Python-Mark-Lutz/dp/0596158106},
	year = 2011
}

**Comment by minihessel** [comment]
@csch0  I even tried to delete a web page entry in the bib, but still it only gets loaded without URL

**Comment by minihessel** [comment]
Now it's working, don't know why. NP then, thanks!

**Comment by csch0** [comment]
@rudvfaden So since you gave me no other feedback I suppose its working now, will push a new minor release later then.

**Comment by rudvfaden** [comment]
Sorry. I forgot. It now shows the right journal. But the wird abbriviation with three dots is back. I.e.

journal = {Chemistry \& …}

**Comment by ntezak** [comment]
The problem persists for me, I usually don't have a journal entry and if I do, it contains the wrong information

**Comment by ntezak** [comment]
Here is an example:

    @article{Gardiner1992WaveFunction,
	author = {Gardiner, CW and Parkins, AS and Zoller, P.},
	booktitle = {APS},
	journal = {APS},
	number = 7,
	pages = 4363,
	publisher = {APS},
	title = {Wave-function quantum stochastic differential equations and quantum-jump simulation methods},
	url = {http://pra.aps.org/abstract/PRA/v46/i7/p4363\_1},
	volume = 46,
	year = 1992
    }

**Comment by csch0** [comment]
@ntezak With the latest testing version of LaTeXing?

**Comment by ntezak** [comment]
It appears to be working in the testing version. Thanks!

**Comment by aeonstone** [comment]
I'm not sure if this issue is related, but since the changes in the Mendeley API I can no longer sync by folder name. I have many items in my mendeley library. Some are articles and books etc. that I would use as references, but some are just pdfs of lecture notes that would never be cited. I keep my  articles in an "Article" folder and I keep the notes in a "Notes" folder. I used to be able to just sync the Article folder with the Remote.bib file but now I cannot. I can sync by Tags but cannot sync by folder.

**Comment by csch0** [comment]
Thanks @aeonstone, realised this too just recently. It is a change in the current API

**Comment by aeonstone** [comment]
Sorry to add more bad news, but I am now experiencing the same issues that redvfaden has had. Journal fields contain the publisher and sometimes a "booktitle" field is created within an article entry. When this happens the publisher is listed as the booktitle. 

I am including a sample entry to illustrate these issues. Also not how the "Pages"  and "Number" fields changes. 

Here is a sample entry produced by mendeley desktop:

@article{albrechtbo1984,
author = {Albrecht, James and Axell, Bo},
journal = {Journal of Political Economy},
number = {5},
pages = {824--840},
publisher = {The University of Chicago Press},
title = {{An Equilibrium Model of Search Unemployment}},
volume = {92},
year = {1984}
}

This is the entry that is imported by Latexing

@article{albrechtbo1984,
	author = {Albrecht, James and Axell, Bo},
	booktitle = {The University of Chicago Press},
	journal = {The University of Chicago Press},
	number = 5,
	pages = {824-840},
	publisher = {The University of Chicago Press},
	title = {An Equilibrium Model of Search Unemployment},
	volume = 92,
	year = 1984
}

**Comment by csch0** [comment]
Ok thanks! Again is this with the latest testing version of LaTeXing??

**Comment by idelft** [comment]
For me, also Journal field missing from Mendeley remote bib.!!! even I do rebuild cache!!

**Comment by csch0** [comment]
@idelft What LaTeXing version? Latest Testing (Then there is a real problem)?

**Comment by idelft** [comment]
my latexing version is 1.2.9

**Comment by csch0** [comment]
Yes if you read this history you can see there are problem with the API, could you please give the latest testing version (http://docs.latexing.com/stable/introduction.html#testing-version) a go and report back if its working.

**Comment by idelft** [comment]
Do you have any guess when the new stable version will be available for updating? becasue I am on a productive system and it is not allowed to use test versions.

**Comment by csch0** [comment]
Once the testers coming back with positive results... but for this feature it will be most likely in the next couple of days..

**Comment by aeonstone** [comment]
Sorry for delayed reply. No I am not using the testing version. I'm finishing my dissertation so the work is mission critical. The only reason I posted is because the issue didn't start with the last update. I printed a copy of my dissertation 3/20 and  the citations were fine, but last week I started having the issues. I'm just exporting the .bib manually for now. Thanks for the great work.

**Comment by minihessel** [comment]
When using the mendely api with web pages, Latexing does not include date accessed.

Here's an example of a citation which has date accessed in mendely, but doesn't in the .bib file:

@misc{Viger2015Performance,
author = {Fournier-Viger, Philippe},
title = {Performance},
url = {http://www.philippe-fournier-viger.com/spmf/index.php?link=performance.php},
year = 2015
}


Also, some web addresses get messed up, for example the address http://www.cs.uic.edu/~kzhao/Papers/00_course_Data_visualization.pdf turns into  http://www.cs.uic.edu/ {extasciitilde}kzhao/Papers/00 course Data visualization.pdf. 


@csch0  any idea when a new version will be released? I'm going to deliver my thesis in 1-2 weeks :)

**Comment by minihessel** [comment]
When using in collection, the Latexing plugin uses "Publisher" for "Book Title". See the example below:

Book title here is "Advances in Knowledge Discovery and Data Mining SE  - 13"  in mendely. 

@incollection{Koh2005Finding,
	author = {Koh, YunSing and Rountree, Nathan},
	booktitle = {Springer Berlin Heidelberg},
	isbn = {978-3-540-26076-9},
	journal = {Springer Berlin Heidelberg},
	pages = {97-106},
	publisher = {Springer Berlin Heidelberg},
	series = {Lecture Notes in Computer Science},
	title = {Finding Sporadic Rules Using Apriori-Inverse},
	url = {http://dx.doi.org/10.1007/11430919\_13},
	volume = 3518,
	year = 2005
}

**Comment by csch0** [comment]
@minihessel I will have a look into this tonight, and contact you by email so we can solve this problems for good. Could you drop am email at info@latexing.com so I can come back to you directly

**Comment by minihessel** [comment]
@csch0 done

**Comment by csch0** [comment]
You send problem (https://github.com/LaTeXing/LaTeXing/issues/105#issuecomment-94405197) should be fixed in the latest testing version already.

**Comment by minihessel** [comment]
@csch0  great, guess we can publish a final version tonight / tomorrow then?

**Comment by csch0** [comment]
Could you check the latest testing version if it solved this problem https://github.com/LaTeXing/LaTeXing/issues/105#issuecomment-94405197

**Comment by minihessel** [comment]
@csch0  it works great. But, I see almost all my citation got updated. Is there any way you can choose between either including DOI or dress?

**Comment by minihessel** [comment]
@csch0 I see you pushed a new version yesterday. Unfortunately web page still doesn't have date retrieved.

**Comment by csch0** [comment]
@minihessel I did? Sorry had some personal issues came in the way, will do it tonight for sure

**Comment by minihessel** [comment]
Sublime said so. At least there was a new version. Okay, great :) @csch0

**Comment by minihessel** [comment]
@csch0 another bug. References with ~ in the url get bugged. Take for example this URL: http://www.cs.uic.edu/~kzhao/Papers/00_course_Data_visualization.pdf

Which ends up being 	url = {http://www.cs.uic.edu/{	extasciitilde}kzhao/Papers/00\_course\_Data\_visualization.pdf} in the bibliography file.

**Comment by csch0** [comment]
Yes same like here or? https://github.com/LaTeXing/LaTeXing/issues/105#issuecomment-94401778

**Comment by minihessel** [comment]
@csch0  ye sorry, I forgot that I already wrote it. I have the flu :-1:

**Comment by csch0** [comment]
@minihessel no problem at all.

**Comment by csch0** [comment]
ok @minihessel just submitted 1.2.10-rc.4 to the testing repository which should fix the missing url date as well as the problem with the ~ in the url.

Could you please check that

**Comment by minihessel** [comment]
Will do first thing in the office tomorrow !

2015-04-21 20:38 GMT+02:00 csch0 <notifications@github.com>:

> ok @minihessel <https://github.com/minihessel> just submitted 1.2.10-rc.4
> to the testing repository which should fix the missing url date as well as
> the problem with the ~ in the url.
>
> Could you please check that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LaTeXing/LaTeXing/issues/105#issuecomment-94899450>.
>



-- 
_____________________________
Med vennlig hilsen Eskil
www.eskil-hesselroth.com

**Comment by adamaltmejd** [comment]
I'm still having issues with journal titles not being included in @article entries. Also trying to cite a working paper that Mendeley sorts as @unpublished, with a series title under "booktitle" that is not included.

Copying the BibTex from Mendeley I have:

@unpublished{Bigoni2014,
author = {Bigoni, Maria and Camera, Gabriele and Casari, Marco},
booktitle = {CFS Working Paper No. 496},
file = {:Users/ad.3103/Dropbox/Reading/Library/Bigoni, Camera, Casari/2014 - Money is More than Memory - Bigoni, Camera, Casari - CFS Working Paper No. 496.pdf:pdf},
mendeley-groups = {Choosing-Money},
title = {{Money is More than Memory}},
year = {2014}
}

@article{Kocherlakota1998,
abstract = {This paper examines the sets of feasible allocations in a large class of economic environments in which commitment is impossible (following Myerson [8], the standard definition of feasibility is adapted to take account of the lack of commitment). The environments feature eithermemoryormoney. Memory is defined as knowledge on the part of an agent of the full histories of all agents with whom he has had direct or indirect contact in the past. Money is defined as an object that does not enter utility or production functions, and is available in fixed supply. The main proposition is that any allocation that is feasible in an environment with money is also feasible in the same environment with memory. Depending on the environment, the converse may or may not be true. Hence, from a technological point of view, money is equivalent to a primitive form of memory.Journal of Economic LiteratureClassification Numbers: E40, C73, D82.},
author = {Kocherlakota, Narayana R.},
doi = {10.1006/jeth.1997.2357},
file = {:Users/ad.3103/Dropbox/Reading/Library/Kocherlakota/1998 - Money Is Memory - Kocherlakota - Journal of Economic Theory.pdf:pdf},
issn = {00220531},
journal = {Journal of Economic Theory},
mendeley-groups = {Choosing-Money},
month = aug,
number = {2},
pages = {232--251},
title = {{Money Is Memory}},
url = {http://www.sciencedirect.com/science/article/pii/S0022053197923577},
volume = {81},
year = {1998}
}

**Comment by adamaltmejd** [comment]
Any news on this?

**Comment by adamaltmejd** [comment]
This still doesn't work for me. Ping @csch0
